# Generated by Django 3.2.7 on 2021-11-25 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_symbol'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Symbol',
            new_name='Stock',
        ),
    ]
