# Generated by Django 3.2.7 on 2021-11-25 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_symbol_stock'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stock',
            new_name='Symbol',
        ),
    ]
