# Generated by Django 3.2.7 on 2021-11-26 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_stock_symbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockpile',
            name='stocks',
            field=models.ManyToManyField(related_name='stockpiles', to='api.Symbol'),
        ),
    ]
