# Generated by Django 3.2.7 on 2021-11-27 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_stockpile_stocks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=5)),
                ('last_refreshed', models.DateTimeField(auto_now_add=True)),
                ('change_day', models.DecimalField(decimal_places=0, default=0, max_digits=3)),
                ('change_week', models.DecimalField(decimal_places=0, default=0, max_digits=3)),
            ],
        ),
    ]
