# Generated by Django 3.2.7 on 2021-11-27 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='daily',
            field=models.JSONField(default=list),
        ),
    ]
